apiVersion: v1
kind: Service
metadata:
  name: guestlist-lb-service
spec:
  type: LoadBalancer
  selector:
    the-app-is: guestlist-pod
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 1111